### PR TITLE
Allows for simulated reads that are present in the sample but not present in the ref db

### PR DESCRIPTION
**Pull request by mahmudhera**
Done by keeping two ref dbs at once, the full db and the truncated db. Most changes are in the workflo.sh script. Changed two other files to control the number of genomes to be considered when creating a genome or a protein reference database.

### CODE REVIEW

**Review by dkoslicki — COMMENTED** [review]
Something odd is up: it appears TPs are not longer being detected. Eg. [impact_of_ref_scale/data/sourmash_performance_metrics_refScale_100_queryScale_1.csv](https://github.com/KoslickiLab/KEGG_sketching_annotation/pull/19/files#diff-3b2001c5b45cb02d61a00fca69d12a5ed8715ea11b3aedd3aab2772fe0835647) used to have ~20 TPs, but now has 0.

**Comment by dkoslicki** [comment]
Re-ran a small test, found a bug (bitscore_threshold was not being set) that caused all Diamond inferences to be zero.

**Review by dkoslicki — APPROVED** [review]

**Comment by mahmudhera** [comment]
Hi @dkoslicki, I am just trying to understand in which script bitscore_threshold was set, could you kindly help me with that?

**Comment by dkoslicki** [comment]
@mahmudhera [this option](https://github.com/KoslickiLab/KEGG_sketching_annotation/blob/main/scripts/calculate_diamond_performance.py#L28) didn't originally have a default, and (mistakenly) wasn't set to be required. So [here](https://github.com/KoslickiLab/KEGG_sketching_annotation/blob/main/experiments/test_experiment/workflow_test_expt.sh#L74) it wasn't being invoked. I set the new default to be zero (i.e. ignore the bit score)

**Comment by mahmudhera** [comment]
Thanks! I got it.

**Pull request merged**
